//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EquityIntegration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://desktop-fo4fjut:7102/IESR/WS/New%20KPLC%20Test/Page/AllStudentsLists")]
        public string EquityIntegration_AllStudentsLists_AllStudentsLists_Service {
            get {
                return ((string)(this["EquityIntegration_AllStudentsLists_AllStudentsLists_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://desktop-fo4fjut:7102/IESR/WS/New%20KPLC%20Test/Page/StudentBankPaymentsCar" +
            "d")]
        public string EquityIntegration_StudentBankPaymentsCard_StudentBankPaymentsCard_Service {
            get {
                return ((string)(this["EquityIntegration_StudentBankPaymentsCard_StudentBankPaymentsCard_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://desktop-fo4fjut:7102/IESR/WS/New%20KPLC%20Test/Page/Student_Bank_Payments")]
        public string EquityIntegration_Student_Bank_Payments_Student_Bank_Payments_Service {
            get {
                return ((string)(this["EquityIntegration_Student_Bank_Payments_Student_Bank_Payments_Service"]));
            }
        }
    }
}
